In [9]:
import numpy as np

In [10]:
a=np.arange(24)

In [12]:
a.ndim

1

In [13]:
print(a)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]


In [35]:
b=a.reshape(4,2,3)

In [36]:
print(b)

[[[ 0  1  2]
  [ 3  4  5]]

 [[ 6  7  8]
  [ 9 10 11]]

 [[12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]]]


In [38]:
x=np.empty([3,2,4],dtype=int)

In [39]:
print(x)

[[[ 0  1  2  3]
  [ 4  5  6  7]]

 [[ 8  9 10 11]
  [12 13 14 15]]

 [[16 17 18 19]
  [20 21 22 23]]]


In [40]:
c=np.ones(3)

In [42]:
d=np.zeros(3)

In [43]:
print(c)
print(d)

[1. 1. 1.]
[0. 0. 0.]
