In [3]:
import numpy as np

In [4]:
X = [[1,2,3],
    [4,5,6],
     [7,8,9]]
Y = [[9,8,7],
     [6,5,4],
     [3,2,1]]

In [5]:
result = np.array(X) + np.array(Y)

In [6]:
print(result)

[[10 10 10]
 [10 10 10]
 [10 10 10]]


In [8]:
difference = np.array(X)-np.array(Y)

In [9]:
print(difference)

[[-8 -6 -4]
 [-2  0  2]
 [ 4  6  8]]


In [10]:
mul = np.array(X) * np.array(Y)

In [11]:
print(mul)

[[ 9 16 21]
 [24 25 24]
 [21 16  9]]


In [12]:
dot = np.dot(X,Y)

In [13]:
print(dot)

[[ 30  24  18]
 [ 84  69  54]
 [138 114  90]]


In [15]:
matr = np.transpose(X)

In [16]:
print(matr)

[[1 4 7]
 [2 5 8]
 [3 6 9]]
