In [1]:
import numpy as np

In [2]:
array = np.array([1,2,3,4,5])

In [3]:
print(array)

[1 2 3 4 5]


In [4]:
zero_dim = np.array(1333331)
print(zero_dim)

1333331


In [5]:
one_dim = np.array([1,2,3])
print(one_dim)

[1 2 3]


In [7]:
two_dim = np.array([[1,2,3],[4,5,6]])

In [8]:
print(two_dim)

[[1 2 3]
 [4 5 6]]


In [19]:
three_dim = np.array([[[1,2,3],[3,4,5],[5,7,8]]])

In [10]:
print(three_dim)

[[[1 2 3]
  [3 4 5]
  [5 7 8]]]


In [31]:
new_array = np.array([1,2],ndmin=5)

In [32]:
print(new_array)

[[[[[1 2]]]]]
