In [1]:
import numpy as np

In [2]:
one_dim = np.array([1,2,3,4,5])

In [6]:
print(one_dim[0:4])

[1 2 3 4]


In [7]:
print(one_dim[1:3])

[2 3]


In [8]:
print(one_dim[:])

[1 2 3 4 5]


In [9]:
print(one_dim[:4])

[1 2 3 4]


In [10]:
print(one_dim[4:])

[5]
